Project/Myapp/urls.py
from django.urls import re_path, path
from Myapp import views, useraccountviews
from Myapp.useraccountviews import UserPasswordChange, EditUserProfile, CustomLoginView, CustomLogoutView


app_name = 'Myapp'

urlpatterns=[
	re_path(r'^$', views.home, name='home'),
	re_path(r'^(?:product-(?P<product_slug>[A-za-z0-9-]+)/)?$', views.detail, name='detail'),
	re_path(r'^order/(?P<product_slug>[A-Za-z0-9-]+)/$', views.order, name='order'),
	re_path(r'^orderconfirmation/(?:product-(?P<product_slug>[A-Za-z0-9-]+))/(?:quantity-(?P<quantity>[\d]+)/)$', views.order_confirmation, name='order-confirm'),
	re_path(r'^cart/$', views.cart, name='cart'),
	re_path(r'^register/$', useraccountviews.register, name='user-register'),
	re_path(r'^login/$', CustomLoginView.as_view(), name='login'),
	re_path(r'^logout/$', CustomLogoutView.as_view(), name='logout'),
	re_path(r'^(?P<user_username>[a-zA-Z0-9!@$_.]+)/$', useraccountviews.user_profile, name='userprofile'),
    re_path(r'^(?P<user_username>[a-zA-Z0-9!@$_.]+)/changepassword/$', UserPasswordChange.as_view(), name='changepassword'),
	re_path(r'^(?P<user_username>[a-zA-Z0-9!@$_.]+)/editprofile/$', EditUserProfile.as_view(), name='edit-profile'),

]

Project/Project/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^Myapp/', include('Myapp.urls')),
    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/Myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.utils.text import slugify
import shortuuid
from django.db.models.signals import pre_save
from django.dispatch import receiver

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError(_('Users must have an email address'))

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    

class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User model with email and username as unique identifiers.
    """
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=30, unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_property_admin = models.BooleanField(_('property admin'), default=False, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True, editable=False)
    profile_image = models.ImageField(_('profile image'), upload_to='Myapp/User/profile_image/', blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        # Returns the first_name plus the last_name, with a space in between.
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        #Returns the short name for the user.
        return self.first_name

    def __str__(self):
        """
        String representation of the user model.
        """
        return self.username

# The Product model
class Product(models.Model):
	Tshirt_Type = [
		('K', 'Kids'),
		('A', 'Adults'),
    ]
	name = models.CharField(max_length=100)
	description = models.JSONField(blank=True)
	price = models.IntegerField(default = 0)
	product_image = models.ImageField(upload_to= 'Myapp/products/images')
	tshirt_type = models.CharField(max_length=1, choices=Tshirt_Type,)
	date_added = models.DateTimeField(auto_now=True)
	slug = models.SlugField(blank=True)
	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		return reverse("Myapp:detail", kwargs={"product_slug": self.slug})
	
	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
		super().save(*args, **kwargs)


# User reviewing the product.
class Review(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	review = models.CharField(max_length=1000)
	

# The order users are gonna make
class Order(models.Model):
	order_id = models.CharField(max_length=22, default='')	
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.PositiveSmallIntegerField()
	ordered_datetime = models.DateTimeField(auto_now_add=True)
	# Payment Choices(for now only Cash on delivery is being implemented)
	class PaymentChoice(models.TextChoices):
		CASH_ON_DELIVERY = 'C',_('Cash on delivery')
		OTHERS = 'O',_('others')
	payment_method = models.CharField(max_length=1, choices=PaymentChoice.choices, default="C")
	# Status of the order
	class OrderStatus(models.TextChoices):
		DELIVERED = 'D',_('Delivered')
		ON_THE_WAY = 'OTW',_('On the way')
		CANCELLED = 'C',_('Cancelled')
	order_status = models.CharField(max_length=3, choices=OrderStatus.choices, blank=True)
	
	# Individual total of a product and its quantity
	@property
	def get_order_total(self):
		total = self.product.price * self.quantity
		return total
	
	def __str__(self):
		return str(self.order_id) + '  ' + self.user.username+ '  ' + self.product.name+ '  ' + str(self.quantity)
	
''' 
We are setting the order_id for the Order model after listening to the pre_save signal
because if we provide the shortuuid as default in the order_id field of the model, everytime we run makemigrations
it creates a new migration for the Order model as the value for the shortuuid will always be different
'''
@receiver(pre_save, sender=Order)
def set_order_id(sender, instance, **kwargs):
    if not instance.order_id:
        instance.order_id = shortuuid.uuid()
	

# The cart for an user	
class UserCart(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	product = models.ManyToManyField(Product, verbose_name="cart items",
		through='CartItem',
		through_fields=('cart', 'product')
		)
	@property
	def get_cart_total(self):
		total = sum([items.price for items in self.product.all()])
		return total
	
	def __str__(self):
		return self.user.username + "'s cart"

class CartItem(models.Model):
	cart = models.ForeignKey(UserCart, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.PositiveSmallIntegerField(default=1)

# This is a proxy model that deals with the orders the user made.
class UserOrder(User):
	class Meta():
		proxy = True

	# To get the total of all the orders the user made
	@property
	def get_total_of_all_orders(self):
		all_orders = self.order_set.all()
		individual_total = [order.get_order_total for order in all_orders]
		total_of_all_orders = sum(num for num in individual_total)
		return total_of_all_orders

Project/Myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
from Myapp.models import User

class UserRegistrationForm(UserCreationForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'unique_email': _("This email address is already in use."),
    }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder':'Username', 'autofocus': False, 'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'placeholder':'Enter your email address', 'autofocus':False, 'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'placeholder':'Enter a password', 'class': 'form-control password-input',})
        self.fields['password2'].widget.attrs.update({'placeholder':'Confirm password', 'class': 'form-control password-input',})

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                self.error_messages['unique_email'],
                code='unique_email',
            )
        return email


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Username or Email')
    error_messages={
        'invalid_login': 'Please enter a correct username or email and password'
    }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set the widget for the username field to a TextInput
        self.fields['username'].widget.attrs.update({'placeholder':'Username or email address', 'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'placeholder':'Enter your password', 'class': 'form-control password-input'})

Project/Myapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
import json

from .models import Product, Order, UserCart


# This is the homepage which displays all the product in the database
def home(request,):
	product_list = Product.objects.all().order_by('date_added')
	paginator = Paginator(product_list, 20)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	
	
	context =  {'page_obj':page_obj,}
	return render(request, 'Myapp/home.html', context)

# This is the detail view of the products
def detail(request, product_slug):
	product = get_object_or_404(Product, slug=product_slug)
	
	print(type(product.description))
	for key in product.description:
		print(key + ":" + product.description[key])
	context = {'product':product,}
	return render(request, 'Myapp/detail.html', context)


# This view is for the order logic
@login_required
def order(request, product_slug):
	product = get_object_or_404(Product, slug=product_slug)
	if request.method == "POST":
		quantity = request.POST.get('quantity')
		context ={
			'product':product,
			'quantity':quantity,
		}
		return render(request, 'Myapp/order.html', context)
	else:
		return redirect("Myapp:detail", product_slug)

	
# The order conformation view
@require_POST
def order_confirmation(request, product_slug, quantity):
	user = request.user
	product = get_object_or_404(Product, slug=product_slug)
	order = Order(user=user, product=product, quantity=quantity, payment_method="Cash on delivery")
	order.save()
	return redirect("Myapp:home")

class MessageEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, messages.Message):
            return str(obj)
        return super().default(obj)
    
# This is the cart functionality
@login_required
def cart(request):
	user = request.user
	# Getting UserCart if its creates or create the cart
	user_cart, created = UserCart.objects.get_or_create(user=user)
	# Getting the product from the fetch api
	if request.method == 'POST':
		data = json.loads(request.body)
		product = data['productId']
		product = Product.objects.get(id=product)
		#adding the product to the user_cart
		if product in user_cart.product.all():
			cartitem = user_cart.cartitem_set.get(product=product)
			cartitem.quantity = cartitem.quantity + 1
			cartitem.save()
			messages.success(request, 'Item quantity added to cart')
		else:
			user_cart.product.add(product)		
			user_cart.save()
			messages.success(request, 'Item added to cart')

		# Get the success message from the session
		message_storage = messages.get_messages(request)
		# Get messages and convert to JSON
		messages_list = [str(message) for message in message_storage]
		json_message = json.dumps(messages_list, cls=MessageEncoder)		
		#return render(request, 'Myapp/home.html')
		return JsonResponse({"message" : json_message})
	# If the method is GET, display the cart page.
	else:
		cart_items = user.usercart.product.all()
		if cart_items.count() == 0:
			context={'no_cart_items':"No items have been added to the cart."}
		else:
			context = {'cart_items': cart_items}
		return render(request, 'Myapp/cart.html', context)

Project/Myapp/templates/Myapp/edit-profile.html
<p>you are at the profile edit page</p>

Project/Myapp/templates/Myapp/login.html
{% extends 'Myapp/main.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'Myapp/Css/register_login.css' %}">
{% endblock css %}

{% block content%}
    <!-- display a one time message after a user successfully creates an account-->
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}

    <!-- A form for logging a user -->
    <div class="container">
        <h1 style="margin-bottom:3px; font-size: 20px; font-weight:100; word-spacing:2px; color:rgba(31, 29, 29, 0.75)">Login to TeeVerse</h1>

        <div class="form-container">
            <form class="form" action="{% url 'Myapp:login' %}" method="post" novalidate>
                <input type="hidden" name="next" value="{{next}}">
                {% csrf_token %}
                {{ form.non_field_errors }}

                {{ form.errors.username }}
                <div class="form-input">
                    <?xml version="1.0" ?><svg height="24" width="24" style="align-self:center" fill="#73797a" enable-background="new 0 0 24 24" id="Layer_1" version="1.0" viewBox="0 0 24 24" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><circle cx="12" cy="8" r="4"/><path d="M12,14c-6.1,0-8,4-8,4v2h16v-2C20,18,18.1,14,12,14z"/></svg>
                    {{ form.username }}
                </div>    
                {{ form.errors.password }}
                <div class="form-input">
                    <?xml version="1.0" ?><svg height="18" width="18" style="align-self:center; margin-left:2px; margin-right: 3px" fill="#676c6d" style="enable-background:new 0 0 1262 1710.258" version="1.1" viewBox="0 0 1262 1710.258" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="lock"><g><path d="M1196.495,713.258H1090V459.592c0-253.285-205.802-459.35-459.001-459.35C377.799,0.242,172,206.442,172,459.892v253.366    H66.686C30.195,713.258,0,742.241,0,778.731v766.42c0,91.079,74.712,165.106,165.792,165.106h931.597    c91.08,0,164.611-74.027,164.611-165.106v-766.42C1262,742.241,1232.985,713.258,1196.495,713.258z M304,459.892    c0-180.588,146.664-327.508,326.999-327.508C811.335,132.384,958,279.168,958,459.592v253.666H304V459.892z M1130,1545.151    c0,18.218-14.395,33.106-32.611,33.106H165.792c-18.216,0-33.792-14.889-33.792-33.106V845.258h998V1545.151z"/><path d="M631,1409.707c36.491,0,66-29.58,66-66.071v-237.854c0-36.49-29.51-66.07-66-66.07c-36.49,0-66,29.58-66,66.07v237.854    C565,1380.127,594.509,1409.707,631,1409.707z"/></g></g><g id="Layer_1"/></svg>
                    {{ form.password }}
                    <?xml version="1.0" ?><svg id="show-password" height="18" width="18" style="align-self:center; margin-left:2px; margin-right: 3px" fill="#676c6d" data-name="015_HEALTH" id="_015_HEALTH" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title/><path d="M12,15c-4.13184,0-7.98-1.21436-10.29395-3.249a.99989.99989,0,1,1,1.32031-1.502C4.98584,11.97168,8.34033,13,12,13s7.01416-1.02832,8.97363-2.751a.99989.99989,0,1,1,1.32031,1.502C19.98,13.78564,16.13184,15,12,15Z" /><path d="M12,18a1,1,0,0,1-1-1V14a1,1,0,0,1,2,0v3A1,1,0,0,1,12,18Z" /><path d="M7.74854,17.66748a.96422.96422,0,0,1-.17041-.01465A.99922.99922,0,0,1,6.76221,16.498L7.26709,13.563a.99981.99981,0,1,1,1.9707.33887l-.50488,2.93506A1,1,0,0,1,7.74854,17.66748Z" /><path d="M3.63574,16.30615a1.00123,1.00123,0,0,1-.94189-1.33643l.97852-2.74463a1,1,0,1,1,1.88379.67188L4.57764,15.6416A1.00085,1.00085,0,0,1,3.63574,16.30615Z"/><path d="M16.25146,17.66748a1,1,0,0,1-.98437-.83057l-.50488-2.93506a.99981.99981,0,0,1,1.9707-.33887l.50488,2.93506a.99922.99922,0,0,1-.81592,1.15479A.96422.96422,0,0,1,16.25146,17.66748Z"/><path d="M20.36426,16.30615a1.00038,1.00038,0,0,1-.94189-.66455L18.44385,12.897a1,1,0,1,1,1.88379-.67187l.97852,2.74463a1.00123,1.00123,0,0,1-.94189,1.33643Z"/></svg>
                    <?xml version="1.0" ?><svg id="hide-password" height="18" width="18" style="align-self:center; margin-left:2px; margin-right: 3px; display:none" fill="#676c6d"viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title/><g data-name="Layer 2" id="Layer_2"><path d="M12,5c-6.54,0-9.76,6.29-9.89,6.55L1.88,12l.22.45C2.24,12.71,5.46,19,12,19s9.76-6.29,9.89-6.55l.22-.45-.22-.45C21.76,11.29,18.54,5,12,5Zm0,12c-4.38,0-7-3.7-7.85-5C5,10.7,7.62,7,12,7s7,3.7,7.85,5C19,13.3,16.38,17,12,17Z"/><path d="M12,8a4,4,0,1,0,4,4A4,4,0,0,0,12,8Zm0,6a2,2,0,1,1,2-2A2,2,0,0,1,12,14Z"/></g></svg>
                </div>
                <input class="submit-btn" type="submit" value="Login">
            </form>
            
        </div>
        <a id="password-reset" href="">Forgot password?</a>

        <div class="rl-link reg">
            <p>Don't have an account? <a href="{% url 'Myapp:user-register' %}">Register</a></p>
        </div>
    </div>
    {% block script %}
        <script>

           
            const showPassword = document.getElementById("show-password");
            const hidePassword = document.getElementById("hide-password");
            const passwordInput = document.querySelector(".password-input");
            showPassword.addEventListener('click', ()=>{
                passwordInput.type = "text";
                hidePassword.style.display="block";
                showPassword.style.display="none";
            });
            hidePassword.addEventListener('click', ()=>{
                passwordInput.type = "password";
                hidePassword.style.display="none";
                showPassword.style.display="block";
            })
        </script>
    {% endblock script %}
   
{% endblock %}

Project/Myapp/templates/Myapp/main.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% block title %}
            <title>TeeVerse.com</title>
        {% endblock title %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/x-icon" href="https://img.icons8.com/cute-clipart/64/null/t.png">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">

        {% load static %}
        <link rel="stylesheet" href="{% static 'Myapp/Css/main.css' %}">
        {% block css %}
            
        {% endblock %}
        

        <script type="text/javascript">
            let User = "{{request.user}}"

            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                    }
                }
                }
                return cookieValue;
            }
            const csrftoken = getCookie('csrftoken');
            
      </script>
    </head>
    <body>
        <div class="navbar-wrapper">
            <!-- Navbar -->
            <div class="navbar">
                
                <div class="brand-logo">
                    <h2><a href="{% url 'Myapp:home' %}">TeeVerse</a></h2>
                </div>
            
                <div class="hamburger-menu">
                    <button class="menu-btn" onclick="openNav()">
                    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                    </button>
                </div>
            
                <div id="mySidenav" class="sidenav">
                    <div class="sidenav-links">
                        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                        <a href="{% url 'Myapp:home' %}" onclick="closeNav()">Home</a>
                    

                    {% if request.user.is_authenticated %}
                        <a class="links" href="{% url 'Myapp:logout' %}" onclick="closeNav()">Logout</a>
                    {% else %}
                        <a href="{% url 'Myapp:login' %}" onclick="closeNav()">login</a>
                        <a href="{% url 'Myapp:user-register' %}" onclick="closeNav()">Sign up</a>
                    {% endif %}
                    
                </div>    
                </div>


                <div class="navbar-content">
                    <div class="nav-links app-links">
                        <a class="links" href="{% url 'Myapp:home' %}">Home</a>
                        <a class="links" href="{% url 'Myapp:home' %}">Custom print</a>
                    </div>
                
                    <div class="nav-links auth-links">
                        <a class="links" href="{% url 'Myapp:user-register' %}">Sign Up</a>
                        <div id="cart-container">
                            <a href="{% url 'Myapp:cart' %}">
                                <svg id="cart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96zM252 160c0 11 9 20 20 20h44v44c0 11 9 20 20 20s20-9 20-20V180h44c11 0 20-9 20-20s-9-20-20-20H356V96c0-11-9-20-20-20s-20 9-20 20v44H272c-11 0-20 9-20 20z"/></svg>
                            </a>
            
                        </div>
                        <div class="profile">
                            {% if request.user.profile_image %}
                                <img class="profile-img" src="{{ request.user.profile_image.url}}" alt="profile image"/>
                            {% else %}
                                <img class="profile-img" src="/static/Myapp/images/default_profile_img.jpg" alt="profile image"/>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>

            </div>
            <div class="profile-card">
                <div class="profile-card-links">
    
                    {% if request.user.is_authenticated %}
                    
                        <a class="links" href="{% url 'Myapp:userprofile' user.username %}">Profile</a>
                        <a class="links" href="#">My orders</a>
                        <a class="links" href="{% url 'Myapp:cart' %}">Cart</a>
                        <a class="links" href="#">My favorites</a>
                        <a class="links" href="#">Change password</a>
                        <a class="links logout-link" href="{% url 'Myapp:logout' %}">Logout</a>
    
                    {% else %}
                        <p>You are not logged !</p>
                        <a class="links login-link" href="{% url 'Myapp:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
        

        {% block content %}
      
        {% endblock content %}
        
        
    
    
        <script type="text/javascript" src="{% static 'Myapp/JS/main.js' %}"></script>
        {% block scripts %}
        
        {% endblock scripts %}
    </body>
</html>

Project/Myapp/templates/Myapp/user_profile.html
{% extends 'Myapp/main.html' %}

{% load static %}

{% block content%}

    <div>
        <div>
            <h3>You are at the profile page.</h3>
            
            <a href="{% url 'Myapp:edit-profile' user.username %}"><h4>Edit profile</h4></a>
            <h3>Username{{ user.username }}</h3>
            <h3>First name{{ user.first_name }}</h3>
            <h3>Last name{{ user.last_name }}</h3>
            <h3>Email{{ user.email }}</h3>                 
            <a href="{% url 'Myapp:changepassword' user.username %}"><h3>Change password</h3></a>
            <a href='#'><h3>Orders</h3></a>
            <a href='#'><h3>Cart</h3></a>    
            <a href='#'><h3>Address</h3></a>
        </div>
    </div>

{% endblock %}

Project/Myapp/templates/Myapp/useraccount.html
{% extends 'Myapp/main.html' %}

{% load static %}

{% block content%}

    <div>
        <div>
            <h3>You are at the profile page.</h3>
            
            <a href="{% url 'Myapp:edit-profile' user.username %}"><h4>Edit profile</h4></a>
            <h3>Username{{ user.username }}</h3>
            <h3>First name{{ user.first_name }}</h3>
            <h3>Last name{{ user.last_name }}</h3>
            <h3>Email{{ user.email }}</h3>                 
            <a href="{% url 'Myapp:changepassword' user.username %}"><h3>Change password</h3></a>
            <a href='#'><h3>Orders</h3></a>
            <a href='#'><h3>Cart</h3></a>    
            <a href='#'><h3>Address</h3></a>
        </div>
    </div>

{% endblock %}